-- PostgreSQL Schema for Logixius Website
-- Run this to create all tables in your PostgreSQL database.

-- Session store table (auto-created by connect-pg-simple, but defined here for completeness)
CREATE TABLE IF NOT EXISTS "user_sessions" (
    "sid" VARCHAR NOT NULL COLLATE "default",
    "sess" JSON NOT NULL,
    "expire" TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("sid")
);
CREATE INDEX IF NOT EXISTS "IDX_session_expire" ON "user_sessions" ("expire");

-- Admins Table
CREATE TABLE IF NOT EXISTS admins (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Certificates Table
CREATE TABLE IF NOT EXISTS certificates (
    id SERIAL PRIMARY KEY,
    intern_id VARCHAR(50) NOT NULL UNIQUE,
    student_name VARCHAR(100) NOT NULL,
    domain VARCHAR(100) NOT NULL,
    start_date DATE,
    end_date DATE,
    duration VARCHAR(50), -- e.g., "3 Months"
    issue_date DATE DEFAULT CURRENT_DATE,
    qr_code_path TEXT,
    certificate_file_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Students Table
CREATE TABLE IF NOT EXISTS students (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    mobile_no VARCHAR(15) NOT NULL UNIQUE,
    gender VARCHAR(10),
    college_name VARCHAR(150),
    degree VARCHAR(100),
    department VARCHAR(100),
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Internship Applications Table
CREATE TABLE IF NOT EXISTS applications (
    id SERIAL PRIMARY KEY,
    student_id INTEGER NOT NULL,
    domain VARCHAR(100) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ONGOING', 'COMPLETED', 'REJECTED')),
    intern_id VARCHAR(50), -- Generated upon approval (Offer Letter stage)
    offer_letter_path VARCHAR(255), -- Path to Offer Letter PDF
    certificate_path VARCHAR(255), -- Path to Completion Certificate PDF
    start_date DATE, -- Set when status becomes ONGOING
    completion_date DATE, -- Set when status becomes COMPLETED
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

-- Insert default admin (Password: admin123)
-- Hash will be generated by setup_db.js
-- INSERT INTO admins (username, password_hash) VALUES ('admin', '$2b$10$...') ON CONFLICT DO NOTHING;
